source "https://github.com/CocoaPods/Specs.git"
platform :ios, '10.0'

inhibit_all_warnings!

def shared_pods
    pod 'Alamofire'
    pod 'AlamofireImage'
end

target 'WheelsCodingChallenge' do
  use_frameworks!

  # Pods for WheelsCodingChallenge
  shared_pods
end

target 'WheelsCodingChallengeTests' do
  inherit! :search_paths
  # Pods for testing
  shared_pods
  pod 'OHHTTPStubs/Swift'
end

target 'WheelsCodingChallengeUITests' do
  inherit! :search_paths
  # Pods for testing
end

post_install do |installer|

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = '$(inherited)'
    end
  end

end